// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8vJmfDNxVWD8aL-TR7Z65hTJ7HK1L-iI',
    appId: '1:1003432109198:web:654bee365c0f81478e15df',
    messagingSenderId: '1003432109198',
    projectId: 'flutter-login-demo-66cee',
    authDomain: 'flutter-login-demo-66cee.firebaseapp.com',
    storageBucket: 'flutter-login-demo-66cee.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdsTOsTOFoBAavad2hG1Uk8hpZZ3lS7SU',
    appId: '1:1003432109198:android:569e868d709602588e15df',
    messagingSenderId: '1003432109198',
    projectId: 'flutter-login-demo-66cee',
    storageBucket: 'flutter-login-demo-66cee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC26d4NbwCLWRP_O-Q1baYLQ4jY9lfHNW8',
    appId: '1:1003432109198:ios:53d6ccaacdb34c9c8e15df',
    messagingSenderId: '1003432109198',
    projectId: 'flutter-login-demo-66cee',
    storageBucket: 'flutter-login-demo-66cee.appspot.com',
    iosClientId: '1003432109198-dfbqgekvprrd1osrcguc9dij5okjirra.apps.googleusercontent.com',
    iosBundleId: 'com.example.firstLog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC26d4NbwCLWRP_O-Q1baYLQ4jY9lfHNW8',
    appId: '1:1003432109198:ios:53d6ccaacdb34c9c8e15df',
    messagingSenderId: '1003432109198',
    projectId: 'flutter-login-demo-66cee',
    storageBucket: 'flutter-login-demo-66cee.appspot.com',
    iosClientId: '1003432109198-dfbqgekvprrd1osrcguc9dij5okjirra.apps.googleusercontent.com',
    iosBundleId: 'com.example.firstLog',
  );
}
